spring:
  application:
    name: api-gateway
server:
  port: 5531
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/